### ISSUE TITLE
Mac app crashes on Google credential submission

### ISSUE THREAD

**Issue by ZacSweers** [mauimauer/portify#1]
☁  portify-0.1-macosx  sh app.sh
portify 0.1
Starting with harmony
   info  - socket.io started
Window Created
Window Ready

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: connect EHOSTUNREACH
    at errnoException (net.js:781:11)
    at connect (net.js:651:19)
    at Socket.connect (net.js:716:9)
    at asyncCallback (dns.js:67:16)
    at Object.onanswer [as oncomplete](dns.js:120:9)
app.sh: line 4: 31772 Bus error: 10           $basedir/data/bin/node --harmony $basedir/data/app.js

**Comment by ZacSweers** [comment]
I believe it's from adding "@gmail.com". When I leave that part out, it works

**Comment by mauimauer** [comment]
The error msg indicates that the app wasn't able to reach it's destination (ie. Google's or Spotify's server). Let's see what I can do here.
