### ISSUE TITLE
Nothing happens after submitting Spotify credentials

### ISSUE THREAD

**Issue by A-Gochnio** [mauimauer/portify#109]
Nothing is happening after I specify  my username number and device password. 
The log just says "Google Login success" and then nothing. The js console is blank, too. Chrome's network tab shows a POST request with my credentials pending, but the response doesn't come back. After a while there's "Failed to load resource: net::ERR_EMPTY_RESPONSE" log in js console.

Portify 0.5.1
Node 0.10.28 x64
Windows 8.1

**Comment by A-Gochnio** [comment]
Yeah, ok, I found a solution. It's because Spotify changed it's API again.
There's a fix provided by @adammw  here: https://gist.github.com/adammw/7f192694c3ed0b13f1f9

You need to copy contents of that file into data/node_modules/spotify-web/lib/spotify.js file, over the previous declaration of Spotify.prototype.sendPong function. Basically replace the block of code that begins like that file, with the contents of that file. Then restart the app.js.

**Comment by chaddjohnson** [comment]
Unfortunately either this still does not work, or it is broken again.

I use Facebook to log into Spotify, so I set a password on my account page and used that. I updated the function using the fix provided by @A-Gochnio, and unfortunately when I look in the Chrome Network debugger tab, the XHR request to http://localhost:3132/spotify/login just sits there and says status "(pending)."
