### ISSUE TITLE
Doesn't support Google 2 factor authentification

### ISSUE THREAD

**Issue by ptiper** [mauimauer/portify#14]
I get 'login failed' when typing my Google Password. Can we add an OTP input (not sure the API supports that)?

**Comment by mauimauer** [comment]
Several users have reported that creating/using app-specific passwords do work when using 2-factor auth. Could you try that?

**Comment by ptiper** [comment]
It worked! Maybe adding a one-liner on the UI when auth fails, telling users to try ASP, could help?

**Comment by tripelbass** [comment]
I just made Portify today, and I'm still seeing this issue, in that I'm using 2-factor auth and ASPs don't work.
