### ISSUE TITLE
Urlencoding in playlist names

### ISSUE THREAD

**Issue by fauxfiction** [mauimauer/portify#26]
After using 0.5 to port my playlists, I noticed they had urlencoded spaces in the playlist names on GMusic.

e.g. Bloc%20Party%20-%20Four

Visible in both the web UI and the droid app - renaming the playlists after they're ported allows spaces as expected.

**Comment by thomasbiddle** [comment]
Confirmed

**Comment by m3nu** [comment]
Seeing that here as well. Rest works fine.

**Comment by scaesic** [comment]
me too

**Comment by thomasbiddle** [comment]
+1
