### ISSUE TITLE
Problem Windows 7 / Windows 8 / Ubuntu 13.04

### ISSUE THREAD

**Issue by melkir** [mauimauer/portify#33]
Hi,
On Windows 7 and Windows 8, after the credential of google and spotify the app force close.
On Ubuntu with your built-in package I have : 
portify 0.4
Starting with harmony
   info  - socket.io started
Window Created
Window Ready
Erreur de segmentation (core dumped)

Edit : Built from source have fix my problem

**Comment by danmilleruk** [comment]
Same issue here.
