### ISSUE TITLE
Crashes on Windows 8 64bit

### ISSUE THREAD

**Issue by blastik** [mauimauer/portify#34]
Hi guys!

Thank for the app in first place.
I'm able to log in successfully to Google and Spotify. Both accounts are premium. I get the crash after I select all the playlist to be imported.
Things I've tried:
- Deactivating antivirus
- Deactivating firewall
- Selecting just one playlist
- Activating XP/7 compatibility
- Running as admin

BTW Where are the logs? I cannot see any crash in the Windows Event viewer...

Thanks!!

**Comment by blastik** [comment]
Will try with linux later...

**Comment by bbeckford** [comment]
I also have this issue on Windows 8 64 bit

**Comment by lesderid** [comment]
Same issue here.

**Comment by kingosticks** [comment]
Same problem but I'm running Windows Vista 64-bit.

**Comment by holblin** [comment]
Same here (win8 64x)

**Comment by rybus** [comment]
Same problem here (Win8 64x). Crashes when connected to both google and spotify and when playlists to transfer are selected

**Comment by blastik** [comment]
fixed by the last version.
FYI, just overwrite the data folder with the newest version at the master branch.
