### ISSUE TITLE
How do i run this on Mac OSX?

### ISSUE THREAD

**Issue by leomavin** [mauimauer/portify#43]
I have downloaded and extracted the mac files. I don't know how to run the app.js file. It opens in xcode and gives me an error. Please explain how I need to run this.

**Comment by alicederyn** [comment]
First, unzip the zip file you downloaded. Then, open Terminal and type:

cd Downloads/portify-0.4-macosx
./app.sh

(You might need to change that first line if you downloaded to a different directory, or there is a newer version of portify available.)

**Comment by alicederyn** [comment]
However, there seems to be a bug in version 0.4 (looks like Google changed its APIs)

**Comment by alicederyn** [comment]
OK, to merge in the new changes, you need to go to https://github.com/mauimauer/portify, click Download ZIP, and unzip the result. Inside, you will find a data folder; select its contents in the finder, and drop them into the data folder in your 0.4 download. (Don't drag the whole data folder, as you need to keep some of the original contents.) Hit "replace all".

Now repeat the terminal instructions above.

Be sure not to select any empty playlists to copy, as that crashes.

**Comment by anshuarya** [comment]
I followed the build instructions, setup Node.js and npm through MacPorts, did the "npm install" command in the "data" folder.  When I run app.js, an iOS simulator starts.  When I try to go to localhost:3132, the page does not load.  Not sure any daemon is running...

Same problem when I download the pre-built package. Running OS X 10.8.5.

UPDATE: Lol silly.  Needed to execute the command "node app.js" and it worked fine :)
