### ISSUE TITLE
How to run on Windows 7?

### ISSUE THREAD

**Issue by tomfisher123** [mauimauer/portify#49]
Hi all, 

Could someone help me out on how I can get this to run on Windows 7? 

I downloaded the portify-0.4-win32.zip (Windows 32bit/64bit) binaries from here: http://www.maui.at/2013/06/portify/ but there are no executables anywhere in the zip folder. 

I also tried downloading the Windows branch here on GitHub, which does have an app.exe file but absolutely nothing happens when I double click on it (no window / error message or anything else) 

I'm sure I'm doing something wrong and have tried googling around but couldn't find any help. Any ideas? 

Thanks!

**Comment by mauimauer** [comment]
Please clone the Github repo and follow https://github.com/mauimauer/portify/blob/master/README.md
