### ISSUE TITLE
Error on Spotify login

### ISSUE THREAD

**Issue by alysania** [mauimauer/portify#54]
Getting "Login Failed" on spotify login.  UserID and password are correct, not sure what's going on.  This just started happening when I updated to .5 - previously, it would log in and then crash right after the spotify log in.

**Comment by dpc** [comment]
I had similiar problem week ago, I did `git pull` and `npm update` and now it works for me.

**Comment by alysania** [comment]
0.5.1 seems to have fixed this issue - works now!
