### ISSUE TITLE
Crash on Windows 8.1

### ISSUE THREAD

**Issue by tlbump** [mauimauer/portify#59]
After unzipping the downloaded file I have attempted to open the app file, but am met with the following error every time:

Error: Object expected
Code: 800A138F
Source: Microsoft 
![windows 8 1 error](https://f.cloud.github.com/assets/5742402/1377871/26dd5e56-3ab4-11e3-9bda-0f79a869fe2e.PNG)
JScript runtime error

**Comment by mauimauer** [comment]
You cannot execute the app.js itself. It has to be run with NodeJs. Please see: https://github.com/mauimauer/portify/blob/master/README.md
