### ISSUE TITLE
Portify can't handle 2 factor authentication

### ISSUE THREAD

**Issue by dereulenspiegel** [mauimauer/portify#67]
Hi,

I'm trying to use portify with my google account which is setup for 2 factor authentication. Every time I enter my username and password, portify reports that the login failed. Instead I would expect an iframe, new window or something like that, asking me for my current OTP.
Is it planned to implement support 2 factor authentication?

**Comment by dries863** [comment]
You can create an application specific password to 'by pass' two tier authentication: https://accounts.google.com/b/0/IssuedAuthSubTokens?hl=nl&hide_authsub=1

**Comment by dereulenspiegel** [comment]
Thanks, application specific passwords didn't crossed my mind. It seems to be working now.
