### ISSUE TITLE
Error: TODO: implement!

### ISSUE THREAD

**Issue by deanpcmad** [mauimauer/portify#84]
I've just tried to use portify but I get this error when signing in with Spotify

![](http://s.vou.pe.s3.amazonaws.com/ede6I.png)

I'm using node v0.10.26

**Comment by dukejansen** [comment]
I believe this is a duplicate of https://github.com/mauimauer/portify/issues/79, which has a workaround documented in a comment by https://github.com/dimfeld.

**Comment by gosuto-inzasheru** [comment]
The workaround described there worked for me!

**Comment by josteink** [comment]
Seconding that. That workaround is still needed at this point, but it does seem to work.

**Comment by alesch** [comment]
I confirm that the workaround is still needed.
